-- 1 PASSO: CRIAR A BASE DE DADOS (DATABASE OU SCHEMA)
-- CRIAR DATABASE OU SHEMA [IF NOT EXISTS] - NOME
-- IF NOT EXISTS: SE JÁ EXISTIR, NÃO CRIE
create database if not exists PROVA_CC1Mc

-- 2 PASSO: ABRIR A BASE DE DADOS PARA USO
-- USE NOME_BASE_DE_DADOS
use PROVA_CC1Mc

-- 3 PASSO: CRIAR AS TABELAS SEM CHAVE ESTRANGEIRA
-- 
-- PRIMARY KEY NÃO PRECISA DE NOT NULL
-- AUTO_INCREMENT
create table if not exists CLIENTES(
num_cliente INT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
rua_cliente VARCHAR(100) NOT NULL,
numero_rua INT,
bairro_cliente VARCHAR(100) NOT NULL,
cidade_cliente VARCHAR(100) NOT NULL,
UF_cliente CHAR(2) NOT NULL,
CEP_cliente VARCHAR(9) NOT NULL
);

create table if not exists CARRO(
ID_carro INT PRIMARY KEY,
registro VARCHAR(20) NOT NULL,
marca VARCHAR(20) NOT NULL
);

-- 4 PASSO: CRIAR AS TABELAS COM FK, POR ORDEM DE NECESSIDADE
create table if not exists APOLICES(
num_apol INT PRIMARY KEY,
valor_apol DECIMAL(10,2) NOT NULL,
cliente INT NOT NULL,
carro INT NOT NULL,
CONSTRAINT CLI_APO FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(num_cliente),
CONSTRAINT CAR_APO FOREIGN KEY (CARRO) REFERENCES CARROS(ID_carro)
);

create table if not exists ACIDENTES(
ID_acidente INT AUTO_INCREMENT PRIMARY KEY,
data_acidente DATE NOT NULL,
hora_acidente TIME NOT NULL,
rua_acid VARCHAR(100) NOT NULL,
num_acid INT,
bairro_acid VARCHAR(100) NOT NULL,
cidade_acid VARCHAR(100) NOT NULL,
UF_acid CHAR(2),
CEP_acid VARCHAR(9),
CLIENTE INT NOT NULL,
CONSTRAINT CLI_ACID FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(num_cliente)
);